version: "3"
services:
  db:
    restart: always
    image: postgres:15
    user: 1000:1000
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready","-U","postgres" ]
      interval: 10s
      retries: 10
    ports:
      - "5432:5432"
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=zaq12wsx
      - POSTGRES_DB=notifier_bot
    volumes:
      - "./docker/postgresql:/var/lib/postgresql/data"
  bot-php:
    restart: always
    user: 1000:1000
    build:
      context: './docker/php-bot'
    volumes:
      - ".:/var/www"
